### ISSUE TITLE
MacOS uses .dylib instead of .so

### ISSUE THREAD

**Issue by bjorn3** [kurtlawrence/papyrus#66]
https://github.com/kurtlawrence/papyrus/blob/4abd8089355bdc9e6419bc00c9d673b717c04438/src/compile/build.rs#L22

**Comment by kurtlawrence** [comment]
Hi @bjorn3, thanks for raising this issue.

Can you please confirm it is working on MacOS on the latest master? #68 should have fixed it but I don't have access to MacOS to confirm.

**Comment by bjorn3** [comment]
It should work now, but I can't test it.
